[package]
name = "UnionFi"
version = "1.0.0"
authors = []

[addresses]
credit_union = "0x1"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
